version: "3"
services:
  news-scraper:
    build: .
    container_name: news-scraper
    command: yarn start
    restart: always
    env_file: .env
    volumes:
      - .:/usr/src

  news-scraper-dev:
    build: .
    container_name: news-scraper-dev
    command: yarn run dev
    env_file: .env
    volumes:
      - ./:/usr/src/app
